apiVersion: v1
kind: Namespace
metadata:
  name: vault-mgmt-e2e

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vault-mgmt-e2e
  namespace: vault-mgmt-e2e
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
  egress:
    - to:
        - podSelector: {}
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
