name: release binaries
on:
  release:
    types: [published]

permissions:
  contents: write
  checks: write
  actions: read
  issues: read
  packages: write
  pull-requests: read
  repository-projects: read
  statuses: read

jobs:
  release:
    name: release binaries
    strategy:
      matrix:
        include:
          - platform: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - platform: macos-latest
            target: x86_64-apple-darwin
          - platform: macos-latest
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --release --target ${{ matrix.target }}
      - run: |
          cd target/${{ matrix.target }}/release/
          tar czvf "vault-mgmt-${{ github.ref_name }}-${{ matrix.target }}".tar.gz \
            vault-mgmt
      - uses: actions/upload-artifact@v3
        with:
          name: vault-mgmt-${{ github.ref_name }}-${{ matrix.target }}.tar.gz
          path: target/${{ matrix.target }}/release/vault-mgmt-${{ github.ref_name }}-${{ matrix.target }}.tar.gz
      - name: Releasing release versions
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/${{ matrix.target }}/release/vault-mgmt-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
